/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.gradle.publish.plugin)
    `java-library`
    `java-gradle-plugin`
    `maven-publish`
}

repositories {
    mavenCentral()
}

group = "de.surala.containertool"
version = "1.0.0"

dependencies {
    api(libs.commons.math3)

    implementation(libs.guava)
    testImplementation(gradleTestKit())
    testImplementation(kotlin("test"))
    testImplementation(libs.jupiter)
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

gradlePlugin {
    website.set("https://github.com/WiktorSurala/ContainerToolPlugin")
    vcsUrl.set("https://github.com/WiktorSurala/ContainerToolPlugin")

    plugins {
        create("dockerPlugin") {
            id = "de.surala.containertool.docker-plugin"
            displayName = "Docker Container Plugin"
            description = "A Gradle plugin for managing Docker containers."
            implementationClass = "de.surala.containertool.dockerplugin.DockerPlugin"
            tags.set(listOf("docker", "container", "manage"))
        }
    }
}